# Generated by Django 2.2.3 on 2020-06-17 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='verified_donation',
            name='mail_sent',
            field=models.BooleanField(default=False),
        ),
    ]
