# Generated by Django 2.2.3 on 2020-06-30 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0002_verified_donation_mail_sent'),
    ]

    operations = [
        migrations.CreateModel(
            name='misc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rec_no_prefix', models.IntegerField(default=0)),
            ],
        ),
    ]
