# Generated by Django 2.2.3 on 2020-07-03 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0003_misc'),
    ]

    operations = [
        migrations.AddField(
            model_name='verified_donation',
            name='recipt_num',
            field=models.IntegerField(default=0),
        ),
    ]
