# Generated by Django 3.1.3 on 2021-01-16 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0004_verified_donation_recipt_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verified_donation',
            name='date_donation',
            field=models.DateField(blank=True),
        ),
    ]
