# Generated by Django 2.2.3 on 2020-06-14 11:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='supporter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.CharField(blank=True, max_length=100, null=True)),
                ('gender', models.CharField(max_length=15, null=True)),
                ('phone_no', models.CharField(max_length=20, unique=True)),
                ('alt_phone_no', models.CharField(max_length=20, null=True)),
                ('email_id', models.EmailField(max_length=254, null=True)),
                ('city', models.CharField(max_length=100, null=True)),
                ('Reference', models.CharField(max_length=100, null=True)),
                ('pan_card', models.CharField(max_length=100, null=True)),
                ('address_a', models.CharField(max_length=100, null=True)),
                ('address_b', models.CharField(max_length=100, null=True)),
                ('address_c', models.CharField(max_length=100, null=True)),
                ('is_constant', models.BooleanField(default=False, null=True)),
                ('amount', models.IntegerField(default=0, null=True)),
                ('is_sponsor', models.BooleanField(default=False, null=True)),
                ('sponsee', models.CharField(max_length=300, null=True)),
                ('is_one_time', models.BooleanField(default=False, null=True)),
                ('resources', models.BooleanField(default=False)),
                ('is_si', models.BooleanField(default=False)),
                ('si_date', models.IntegerField(null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('profession', models.CharField(max_length=200, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('last_generated', models.IntegerField(default=6)),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_edited', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
