# Generated by Django 2.2.3 on 2020-07-03 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supporters', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supporter',
            name='last_generated',
            field=models.IntegerField(null=True),
        ),
    ]
