# Generated by Django 3.1.3 on 2021-01-16 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supporters', '0003_auto_20210116_0945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supporter',
            name='name',
            field=models.CharField(help_text='hello', max_length=100),
        ),
    ]
