# Generated by Django 3.1.3 on 2021-01-16 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supporters', '0004_auto_20210116_0948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supporter',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
