# Generated by Django 3.1.3 on 2021-01-16 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supporters', '0005_auto_20210116_0949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supporter',
            name='is_constant',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='supporter',
            name='is_one_time',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='supporter',
            name='is_sponsor',
            field=models.BooleanField(default=False),
        ),
    ]
