# Generated by Django 3.1.3 on 2021-03-26 10:13

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usersreg', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='expense',
            fields=[
                ('reimb_id', models.IntegerField(primary_key=True, serialize=False)),
                ('added_by', models.CharField(max_length=250)),
                ('event_name', models.CharField(blank=True, max_length=250, null=True)),
                ('expense_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('vendor_name', models.CharField(max_length=250)),
                ('is_advance', models.BooleanField(default=False)),
                ('is_settled', models.BooleanField(default=False)),
                ('added_on', models.DateField(default=datetime.datetime(2021, 3, 26, 10, 13, 15, 244146, tzinfo=utc))),
                ('file', models.FileField(null=True, upload_to='')),
                ('remarks', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='approved',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('settle_date', models.DateField(verbose_name=datetime.datetime(2021, 3, 26, 10, 13, 15, 244146, tzinfo=utc))),
                ('payment_date', models.DateField()),
                ('expense_head', models.CharField(max_length=250)),
                ('category', models.CharField(max_length=250)),
                ('sub_category', models.CharField(max_length=250)),
                ('amount_approved', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('settled_comments', models.CharField(max_length=1000)),
                ('exp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exptemp.expense')),
                ('settled_by', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='usersreg.member')),
            ],
        ),
    ]
