# Generated by Django 3.1.3 on 2021-03-26 10:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('exptemp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='track_id',
            field=models.IntegerField(default=12),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='approved',
            name='settle_date',
            field=models.DateField(verbose_name=datetime.datetime(2021, 3, 26, 10, 29, 56, 224461, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='expense',
            name='added_on',
            field=models.DateField(default=datetime.datetime(2021, 3, 26, 10, 29, 56, 224461, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='expense',
            name='remarks',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
