# Generated by Django 3.1.3 on 2021-03-27 16:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('exptemp', '0002_auto_20210326_1130'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='track_id',
        ),
        migrations.AlterField(
            model_name='approved',
            name='settle_date',
            field=models.DateField(verbose_name=datetime.datetime(2021, 3, 27, 16, 24, 6, 498750, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='expense',
            name='added_on',
            field=models.DateField(default=datetime.datetime(2021, 3, 27, 16, 24, 6, 498750, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='expense',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='expense',
            name='remarks',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='expense',
            name='vendor_name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
