# Generated by Django 3.1.3 on 2021-04-05 15:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('exptemp', '0005_auto_20210328_0726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='added_on',
            field=models.DateField(default=datetime.datetime(2021, 4, 5, 15, 4, 17, 459875, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='settled',
            name='expense_head',
            field=models.CharField(choices=[('prog', 'Program Cost'), ('admin', 'Administrative Cost'), ('funds', 'Fundraising Cost')], max_length=250),
        ),
        migrations.AlterField(
            model_name='settled',
            name='settle_date',
            field=models.DateField(verbose_name=datetime.datetime(2021, 4, 5, 15, 4, 17, 458874, tzinfo=utc)),
        ),
    ]
