# Generated by Django 3.1.3 on 2021-04-06 23:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('exptemp', '0006_auto_20210405_1704'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='settled',
            name='category',
        ),
        migrations.RemoveField(
            model_name='settled',
            name='expense_head',
        ),
        migrations.RemoveField(
            model_name='settled',
            name='sub_category',
        ),
        migrations.AddField(
            model_name='expense',
            name='category',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='expense_head',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='sub_category',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='expense',
            name='added_on',
            field=models.DateField(default=datetime.datetime(2021, 4, 6, 23, 35, 52, 829702, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='settled',
            name='settle_date',
            field=models.DateField(verbose_name=datetime.datetime(2021, 4, 6, 23, 35, 52, 828735, tzinfo=utc)),
        ),
    ]
