# Generated by Django 3.1.3 on 2021-04-12 14:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('exptemp', '0007_auto_20210407_0135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='added_on',
            field=models.DateField(default=datetime.datetime(2021, 4, 12, 14, 50, 47, 897923, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='settled',
            name='settle_date',
            field=models.DateField(default=datetime.datetime(2021, 4, 12, 14, 50, 47, 896920, tzinfo=utc)),
        ),
    ]
