# Generated by Django 2.2.3 on 2020-06-14 11:31

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usersreg', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='advanced',
            fields=[
                ('adv_id', models.IntegerField(primary_key=True, serialize=False)),
                ('event_name', models.CharField(blank=True, max_length=250, null=True)),
                ('adv_desc', models.CharField(max_length=1000)),
                ('event_date', models.DateField()),
                ('clearer', models.CharField(max_length=250)),
                ('added_on', models.DateField(default=datetime.datetime(2020, 6, 14, 11, 31, 53, 535671, tzinfo=utc))),
                ('status', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='expenditure',
            fields=[
                ('reimb_id', models.IntegerField(primary_key=True, serialize=False)),
                ('event_name', models.CharField(blank=True, max_length=250, null=True)),
                ('event_desc', models.CharField(choices=[('prog', 'Program Cost'), ('admin', 'Administrative Cost'), ('funds', 'Fundraising Cost')], max_length=250)),
                ('event_date', models.DateField()),
                ('bill_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('bill_no', models.CharField(max_length=250)),
                ('vendor_name', models.CharField(max_length=250)),
                ('approve_comments', models.CharField(max_length=1000)),
                ('clear_comments', models.CharField(max_length=1000)),
                ('is_advanced', models.BooleanField(default=False)),
                ('adv_amount', models.DecimalField(decimal_places=3, default=0, max_digits=8)),
                ('clearer', models.CharField(max_length=250)),
                ('approved', models.BooleanField(default=False)),
                ('cleared', models.BooleanField(default=False)),
                ('added_on', models.DateField(default=datetime.datetime(2020, 6, 14, 11, 31, 53, 535671, tzinfo=utc))),
                ('added_by', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='usersreg.member')),
                ('adv_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expenditure.advanced')),
            ],
        ),
        migrations.CreateModel(
            name='exp_items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_no', models.CharField(max_length=250)),
                ('desc', models.CharField(max_length=1000)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('file', models.FileField(upload_to='')),
                ('exp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expenditure.expenditure')),
            ],
        ),
    ]
