# Generated by Django 2.2.3 on 2020-06-15 05:01

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('usersreg', '0001_initial'),
        ('expenditure', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expenditure',
            old_name='clearer',
            new_name='approver',
        ),
        migrations.RenameField(
            model_name='expenditure',
            old_name='approved',
            new_name='is_approved',
        ),
        migrations.RenameField(
            model_name='expenditure',
            old_name='cleared',
            new_name='is_cleared',
        ),
        migrations.RemoveField(
            model_name='expenditure',
            name='approve_comments',
        ),
        migrations.RemoveField(
            model_name='expenditure',
            name='clear_comments',
        ),
        migrations.AlterField(
            model_name='advanced',
            name='added_on',
            field=models.DateField(default=datetime.datetime(2020, 6, 15, 5, 0, 52, 21989, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='expenditure',
            name='added_on',
            field=models.DateField(default=datetime.datetime(2020, 6, 15, 5, 0, 52, 21989, tzinfo=utc)),
        ),
        migrations.CreateModel(
            name='cleared',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cleared_date', models.DateField(verbose_name=datetime.datetime(2020, 6, 15, 5, 0, 52, 31985, tzinfo=utc))),
                ('amount_cleared', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('clear_comments', models.CharField(max_length=1000)),
                ('cleared_by', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='usersreg.member')),
                ('exp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expenditure.expenditure')),
            ],
        ),
        migrations.CreateModel(
            name='approved',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approval_date', models.DateField(verbose_name=datetime.datetime(2020, 6, 15, 5, 0, 52, 31985, tzinfo=utc))),
                ('expense_head', models.CharField(max_length=250)),
                ('category', models.CharField(max_length=250)),
                ('sub_category', models.CharField(max_length=250)),
                ('amount_approved', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('clearer', models.CharField(max_length=250)),
                ('approve_comments', models.CharField(max_length=1000)),
                ('approved_by', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='usersreg.member')),
                ('exp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expenditure.expenditure')),
            ],
        ),
    ]
