# Generated by Django 2.2.3 on 2020-06-15 05:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('expenditure', '0003_auto_20200615_1123'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exp_items',
            name='bill_no',
        ),
        migrations.RemoveField(
            model_name='exp_items',
            name='file',
        ),
        migrations.AddField(
            model_name='exp_items',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='exp_items',
            name='qty',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='expenditure',
            name='file',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='advanced',
            name='added_on',
            field=models.DateField(default=datetime.datetime(2020, 6, 15, 5, 57, 21, 270193, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='approved',
            name='approval_date',
            field=models.DateField(verbose_name=datetime.datetime(2020, 6, 15, 5, 57, 21, 270193, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='cleared',
            name='cleared_date',
            field=models.DateField(verbose_name=datetime.datetime(2020, 6, 15, 5, 57, 21, 270193, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='expenditure',
            name='added_on',
            field=models.DateField(default=datetime.datetime(2020, 6, 15, 5, 57, 21, 270193, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='expenditure',
            name='bill_date',
            field=models.DateField(default=datetime.datetime(2020, 6, 15, 5, 57, 21, 270193, tzinfo=utc)),
        ),
    ]
