# Generated by Django 2.2.3 on 2020-06-16 10:35

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('usersreg', '0001_initial'),
        ('expenditure', '0006_auto_20200615_2038'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advanced',
            name='clearer',
        ),
        migrations.RemoveField(
            model_name='approved',
            name='clearer',
        ),
        migrations.RemoveField(
            model_name='expenditure',
            name='approver',
        ),
        migrations.AddField(
            model_name='advanced',
            name='added_by',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='usersreg.member'),
        ),
        migrations.AddField(
            model_name='advanced',
            name='cleared_by',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='clearer', to='usersreg.member'),
        ),
        migrations.AddField(
            model_name='advanced',
            name='cleared_on',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='advanced',
            name='is_attached',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='advanced',
            name='is_cleared',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='advanced',
            name='added_on',
            field=models.DateField(default=datetime.datetime(2020, 6, 16, 10, 35, 10, 196666, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='approved',
            name='approval_date',
            field=models.DateField(verbose_name=datetime.datetime(2020, 6, 16, 10, 35, 10, 199665, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='cleared',
            name='cleared_date',
            field=models.DateField(verbose_name=datetime.datetime(2020, 6, 16, 10, 35, 10, 199665, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='expenditure',
            name='added_on',
            field=models.DateField(default=datetime.datetime(2020, 6, 16, 10, 35, 10, 197667, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='expenditure',
            name='bill_date',
            field=models.DateField(default=datetime.datetime(2020, 6, 16, 10, 35, 10, 197667, tzinfo=utc)),
        ),
    ]
