# Generated by Django 2.2.3 on 2020-06-16 10:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('expenditure', '0007_auto_20200616_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advanced',
            name='added_on',
            field=models.DateField(default=datetime.datetime(2020, 6, 16, 10, 48, 59, 866166, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='advanced',
            name='status',
            field=models.CharField(default='Submitted', max_length=250),
        ),
        migrations.AlterField(
            model_name='approved',
            name='approval_date',
            field=models.DateField(verbose_name=datetime.datetime(2020, 6, 16, 10, 48, 59, 869165, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='cleared',
            name='cleared_date',
            field=models.DateField(verbose_name=datetime.datetime(2020, 6, 16, 10, 48, 59, 869165, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='expenditure',
            name='added_on',
            field=models.DateField(default=datetime.datetime(2020, 6, 16, 10, 48, 59, 867165, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='expenditure',
            name='bill_date',
            field=models.DateField(default=datetime.datetime(2020, 6, 16, 10, 48, 59, 867165, tzinfo=utc)),
        ),
    ]
