# Generated by Django 2.2.3 on 2020-06-16 10:59

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('expenditure', '0008_auto_20200616_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advanced',
            name='added_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usersreg.member'),
        ),
        migrations.AlterField(
            model_name='advanced',
            name='added_on',
            field=models.DateField(default=datetime.datetime(2020, 6, 16, 10, 58, 33, 114298, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='advanced',
            name='event_name',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='approved',
            name='approval_date',
            field=models.DateField(verbose_name=datetime.datetime(2020, 6, 16, 10, 58, 33, 117297, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='cleared',
            name='cleared_date',
            field=models.DateField(verbose_name=datetime.datetime(2020, 6, 16, 10, 58, 33, 118297, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='expenditure',
            name='added_on',
            field=models.DateField(default=datetime.datetime(2020, 6, 16, 10, 58, 33, 116297, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='expenditure',
            name='bill_date',
            field=models.DateField(default=datetime.datetime(2020, 6, 16, 10, 58, 33, 116297, tzinfo=utc)),
        ),
    ]
