# Generated by Django 2.2.3 on 2020-06-16 11:14

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('expenditure', '0009_auto_20200616_1629'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advanced',
            name='cleared_by',
        ),
        migrations.RemoveField(
            model_name='advanced',
            name='cleared_on',
        ),
        migrations.AddField(
            model_name='cleared',
            name='is_adv',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='advanced',
            name='added_on',
            field=models.DateField(default=datetime.datetime(2020, 6, 16, 11, 14, 49, 928509, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='approved',
            name='approval_date',
            field=models.DateField(verbose_name=datetime.datetime(2020, 6, 16, 11, 14, 49, 937160, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='cleared',
            name='cleared_date',
            field=models.DateField(verbose_name=datetime.datetime(2020, 6, 16, 11, 14, 49, 938158, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='expenditure',
            name='added_on',
            field=models.DateField(default=datetime.datetime(2020, 6, 16, 11, 14, 49, 928509, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='expenditure',
            name='bill_date',
            field=models.DateField(default=datetime.datetime(2020, 6, 16, 11, 14, 49, 928509, tzinfo=utc)),
        ),
    ]
